src/InlasoftWeb/Models/Caso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace InlasoftWeb.Models
{
    public class Caso : BaseModel
    {
        [Key]
        public string CasoId { get; set; }
        [Required]
        [Display(Name = "Fecha Inicio")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DataType(DataType.Date)]
        public DateTime FechaInicio { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        [Required]
        public string Contraparte { get; set; }
        public string Catastro { get; set; }
        [Required]
        public virtual Servicio Servicio { get; set; }
        [Required]
        public virtual Firma Firma { get; set; }
        [Required]
        public virtual Cliente Cliente { get; set; }
        public virtual Sucursal Sucursal { get; set; }

        public virtual List<Audiencia> Audiencias { get; set; }
        public virtual List<Gestion> Gestiones { get; set; }
        public virtual List<Documento> Documentos { get; set; }
        public virtual List<Reunion> Reuniones { get; set; }
    }
}

src/InlasoftWeb/ViewModels/CasoViewModel.cs
using InlasoftWeb.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InlasoftWeb.ViewModels
{
    public class CasoViewModel
    {
        [Key]
        public string CasoId { get; set; }
        [Display(Name = "Fecha Inicio")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DataType(DataType.Date)]
        public DateTime FechaInicio { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        public string Contraparte { get; set; }
        public string Catastro { get; set; }
        public string Materia { get; set; }
        public string Servicio { get; set; }
        public string Firma { get; set; }
        public string Cliente { get; set; }
        public string Sucursal { get; set; }

        public static explicit operator CasoViewModel (Caso caso)
        {
            return new CasoViewModel {
                CasoId = caso.CasoId,
                FechaInicio = caso.FechaInicio,
                Descripcion = caso.Descripcion,
                Contraparte = caso.Contraparte,
                Catastro = caso.Catastro,
                Materia = caso.Servicio.Materia.MateriaNombre,
                Servicio = caso.Servicio.ServicioNombre,
                Firma = caso.Firma.FirmaNombre,
                Cliente = caso.Cliente.ClienteNombre,
                Sucursal = caso.Sucursal.SucursalNombre
            };
        }
    }
}

src/InlasoftWeb/Controllers/CasosController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InlasoftWeb.Database;
using InlasoftWeb.Models;
using InlasoftWeb.Extensions;
using Microsoft.AspNetCore.Identity;
using System;
using InlasoftWeb.ViewModels;

namespace InlasoftWeb.Controllers
{
    public class CasosController : Controller
    {
        private readonly InlasoftDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public CasosController(InlasoftDbContext context, UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: Casos
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            var userFirmaId = User.Identity.GetFirmaId();
            var caso = GetCasosByFirmaId(userFirmaId);

            #region Table Filtering
            ViewData["CurrentFilter"] = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                caso = caso.Where(c => c.Descripcion.Contains(searchString));

            }

            #endregion

            return View(await caso.AsNoTracking().ToListAsync());
        }

        // GET: Casos/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFirmaId = User.Identity.GetFirmaId();
            var caso = GetCasosByFirmaIdAndCasoId(userFirmaId, id);
            if (caso == null)
            {
                return NotFound();
            }
            return View(await caso.AsNoTracking().SingleOrDefaultAsync());
        }

        private IQueryable<CasoViewModel> GetCasosByFirmaId(string firmaId)
        {
            var caso = _context.Casos
                .Include(c => c.Servicio)
                    .ThenInclude(s => s.Materia)
                .Include(c => c.Cliente)
                .Include(c => c.Sucursal)
                .Include(c => c.Firma)
                .Where(c => c.Firma.FirmaId == firmaId)
                .Select(x => (CasoViewModel)x);
            return caso;
        }

        private IQueryable<CasoDetailViewModel> GetCasosByFirmaIdAndCasoId(string firmaId, string casoId)
        {
            var caso = _context.Casos
                .Include(c => c.Audiencias)
                    .ThenInclude(a => a.Abogado)
                .Include(c => c.Gestiones)
                    .ThenInclude(a => a.Abogado)
                .Include(c => c.Documentos)
                    .ThenInclude(a => a.Abogado)
                .Include(c => c.Reuniones)
                    .ThenInclude(r => r.Abogado)
                .Include(c => c.Cliente)
                .Include(c => c.Sucursal)
                .Where(c => c.Firma.FirmaId == firmaId && c.CasoId == casoId)
                .Select(x => (CasoDetailViewModel)x);
            return caso;
        }

    }
}

src/InlasoftWeb/Views/Casos/Details.cshtml
@model InlasoftWeb.ViewModels.CasoDetailViewModel
@using InlasoftWeb.Helpers

@{
    ViewData["Title"] = "Details";
    ViewData["tab"] = ViewContext.HttpContext.Request.Query["tab"].ToString();
}

<h2>Detalles de Caso</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Descripcion)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contraparte)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Contraparte)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Catastro)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Catastro)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cliente)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sucursal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sucursal)
        </dd>
    </dl>

    <ul class="nav nav-tabs">
        <li class="@TabNavigationHelper.SetActiveTab(ViewData["tab"].ToString(), string.Empty)">@Html.ActionLink("Audiencias", "Details", "Casos", new { id = Model.CasoId})</li>
        <li class="@TabNavigationHelper.SetActiveTab(ViewData["tab"].ToString(), "Gestiones")">@Html.ActionLink("Gestiones", "Details", "Casos", new { id = Model.CasoId, tab = "Gestiones" })</li>
        <li class="@TabNavigationHelper.SetActiveTab(ViewData["tab"].ToString(), "Documentos")">@Html.ActionLink("Documentos", "Details", "Casos", new { id = Model.CasoId, tab = "Documentos" })</li>
        <li class="@TabNavigationHelper.SetActiveTab(ViewData["tab"].ToString(), "Reuniones")">@Html.ActionLink("Reuniones", "Details", "Casos", new { id = Model.CasoId, tab = "Reuniones" })</li>
    </ul>
    @{
        switch (ViewData["tab"].ToString())
        {
            case "":
                @Html.Partial("_AudienciasList", Model.Audiencias)
                break;
            case "Gestiones":
                @Html.Partial("_GestionesList", Model.Gestiones)
                break;
            case "Documentos":
                @Html.Partial("_DocumentosList", Model.Documentos)
                break;
            case "Reuniones":
                @Html.Partial("_ReunionesList", Model.Reuniones)
                break;
        }
    }
</div>
<div>
    <a asp-action="Index">Volver a Listado</a>
</div>

src/InlasoftWeb/Views/Casos/Index.cshtml
@model IEnumerable<InlasoftWeb.ViewModels.CasoViewModel>

@{
    ViewData["Title"] = "Index";
}
<h2>Listado de Casos</h2>
<form asp-action="Index" method="get">
    <div class="col-md-12">
        <span>Buscar :
            <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Buscar" class="btn btn-default" />
        </span>
    </div>
</form>
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.CasoId).Titled("Codigo").Sortable(true);
        columns.Add(model => model.Descripcion).Titled("Descripcion");

        columns.Add(model => model.Materia).Titled("Materia");
        columns.Add(model => model.Servicio).Titled("Servicio");
        columns.Add(model => model.Sucursal).Titled("Sucursal");
        columns.Add(model => model.Contraparte).Titled("Contraparte");
        columns.Add(Model => Html.ActionLink(string.Empty, "Details", "Casos", new { id = Model.CasoId }, new { @class = "glyphicon glyphicon-folder-open" }));

    })
    .Sortable()
    .Pageable(pager => {
        pager.RowsPerPage = 25;
        pager.PagesToDisplay = 5;
    })
)